# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-07 22:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0007_auto_20190107_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='falta',
            field=models.DateTimeField(default=datetime.date(2019, 1, 7)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='fmodificacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
