# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-09 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0009_auto_20190109_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fmodificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
