# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-02 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0016_compania_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recarga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField(default=0)),
                ('falta', models.DateTimeField(auto_now_add=True, null=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='precios.Plan')),
            ],
        ),
    ]
