# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-28 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0024_auto_20190612_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(default='', max_length=8)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'precios_proveedor',
                'managed': False,
            },
        ),
    ]
