# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='barcode',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
