# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-06-17 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='compania',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='configuracion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='detallemovimiento',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='movimiento',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='recarga',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tipomovimiento',
            options={'managed': False},
        ),
    ]
