# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-29 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(default='', max_length=8)),
                ('description', models.CharField(max_length=255)),
                ('es_persona_moral', models.BooleanField(default=False)),
                ('es_proveedor', models.BooleanField(default=False)),
                ('es_cliente', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'precios_persona',
                'managed': False,
            },
        ),
    ]
