# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-04-08 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0003_auto_20200810_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaprecioproveedor',
            name='alta_rotacion',
            field=models.DecimalField(decimal_places=0, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='historiaprecioproveedor',
            name='caja',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='historiaprecioproveedor',
            name='codigobarras',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historiaprecioproveedor',
            name='precioMayoreo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='historiaprecioproveedor',
            name='precioPublico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='historiaprecioproveedor',
            name='unidad',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historiaprecioproveedor',
            name='precioCompra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
