# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2022-02-17 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0004_auto_20210408_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioPrecio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoInterno', models.CharField(max_length=20, unique=True)),
                ('codigoProveedor', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('precioCompraAnt', models.IntegerField(default=0)),
                ('precioCompra', models.DecimalField(decimal_places=2, max_digits=7)),
                ('precioVenta', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'precios_cambioprecio',
                'managed': False,
            },
        ),
    ]
