# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0005_movimiento_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallemovimiento',
            name='barcode',
            field=models.CharField(max_length=30),
        ),
    ]
