# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-07 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0006_auto_20180308_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='description',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='minimoexist',
            field=models.IntegerField(default=0),
        ),
    ]
