# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-05 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0011_auto_20190131_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigoproveedor',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='producto',
            name='maximoexist',
            field=models.IntegerField(default=0),
        ),
    ]
