# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-07 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0012_auto_20190205_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='codigo',
            field=models.CharField(default='', max_length=5),
        ),
    ]
