# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-12 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0013_categoria_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomovimiento',
            name='prioridad',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
    ]
