# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-26 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0015_tipomovimiento_factor_conta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(default='', max_length=5)),
                ('description', models.CharField(max_length=255)),
                ('imagen', models.CharField(max_length=50)),
                ('comision', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plan', models.CharField(default='', max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('monto', models.IntegerField(default=0)),
                ('compania', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='precios.Compania')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='precios.Producto')),
            ],
        ),
    ]
