# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-03 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0018_auto_20190502_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='recarga',
            name='codigoautorizacion',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='recarga',
            name='error',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
