# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-17 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0020_plan_tipoplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(default='', max_length=30)),
                ('valor', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='ubicacion',
            field=models.CharField(default='', max_length=255),
        ),
    ]
