# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-23 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0021_auto_20190517_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='puede_venderse',
            field=models.BooleanField(default=True),
        ),
    ]
