# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-06-17 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings
from django.contrib.auth.models import User

class Migration(migrations.Migration):

    initial = True

    dependencies = [
          ('auth', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(default='', max_length=5)),
                ('description', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='precios.Categoria')),
            ],
            options={
                'db_table': 'precios_categoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(default='', max_length=5)),
                ('description', models.CharField(max_length=255)),
                ('imagen', models.CharField(max_length=50)),
                ('comision', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'precios_compania',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(default='', max_length=30)),
                ('valor', models.CharField(default='', max_length=300)),
            ],
            options={
                'db_table': 'precios_configuracion',
                'managed': True,
            },
        ),

        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('factor', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('factor_conta', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('prioridad', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
            ],
            options={
                'db_table': 'precios_tipomovimiento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='precios.TipoMovimiento')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('description', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'precios_movimiento',
                'managed': True,
            },
        ),

        migrations.CreateModel(
            name='DetalleMovimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='precios.Movimiento')),
                ('barcode', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField(default=0)),
                ('precioCompra', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('precioVenta', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'db_table': 'precios_detallemovimiento',
                'managed': True,
            },
        ),

        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(default='', max_length=8)),
                ('description', models.CharField(max_length=255)),
                ('es_persona_moral', models.BooleanField(default=False)),
                ('es_proveedor', models.BooleanField(default=False)),
                ('es_cliente', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'precios_persona',
                'managed': True,
            },
        ),

        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoInterno', models.CharField(max_length=20, unique=True)),
                ('codigoProveedor', models.CharField(max_length=50)),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='precios.Persona')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='precios.Categoria')),
                ('barcode', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('descriptionCorta', models.CharField(max_length=255)),
                ('existencia', models.IntegerField(default=0)),
                ('minimoexist', models.IntegerField(default=0)),
                ('maximoexist', models.IntegerField(default=0)),
                ('precioCompra', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precioVenta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ubicacion', models.CharField(default='', max_length=255)),
                ('unidadVenta', models.CharField(max_length=30)),
                ('falta', models.DateTimeField()),
                ('fmodificacion', models.DateTimeField(blank=True, null=True)),
                ('puede_venderse', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'precios_producto',
                'managed': True,
            },
        ),

        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plan', models.CharField(default='', max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('monto', models.IntegerField(default=0)),
                ('tipoplan', models.IntegerField(default=0)),
                ('compania', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='precios.Compania')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='precios.Producto')),
            ],
            options={
                'db_table': 'precios_plan',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Recarga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='precios.Plan')),
                ('celular', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('monto', models.IntegerField(default=0)),
                ('falta', models.DateTimeField(auto_now_add=True, null=True)),
                ('estatus', models.CharField(default='EN PROCESO', max_length=20)),
                ('error', models.CharField(default='', max_length=1024)),
                ('codigoautorizacion', models.CharField(default='', max_length=30)),
            ],
            options={
                'db_table': 'precios_recarga',
                'managed': True,
            },
        ),

    ]
